# Generated by Django 6.1.1 on 2026-09-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threads',
            old_name='memebers',
            new_name='members',
        ),
    ]
